language: generic

dist: trusty

services:
- docker

env:
  global:
  - BRANCH=product_tests_downloaded_artifacts
  - ARTIFACTS_S3_URI=s3://teradata-presto/travis_build_artifacts/Teradata/presto

before_install: sudo pip install awscli

install:
- LAST_BUILD=`aws s3 ls $ARTIFACTS_S3_URI/$BRANCH/ --no-sign-request | awk '{print $2}' | sed 's/.$//' | sort -n | tail -n1`
- |
  aws s3 sync ${ARTIFACTS_S3_URI}/${BRANCH}/${LAST_BUILD} /tmp/artifacts \
    --exclude '*' \
    --include 'git-revision.txt' \
    --include 'presto-server-*.tar.gz' \
    --include 'presto-cli-*-executable.jar' \
    --include 'presto-product-tests-*-executable.jar' \
    --no-sign-request
- git clone --depth=50 --branch=${BRANCH} https://github.com/Teradata/presto.git
- cd presto
- git checkout `cat /tmp/artifacts/git-revision.txt`
- tar -xf /tmp/artifacts/presto-server-*.tar.gz -C /tmp/

script: |
  export PRESTO_SERVER_DIR=/tmp/presto-server-*
  export PRESTO_CLI_JAR=/tmp/artifacts/presto-cli-*-executable.jar
  export PRODUCT_TESTS_JAR=/tmp/artifacts/presto-product-tests-*-executable.jar
  ./presto-product-tests/bin/run_on_docker.sh multinode -x quarantine,big_query,storage_formats,profile_specific_tests

